kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: paradox
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    apiVersion: kubeadm.k8s.io/v1beta4
    nodeRegistration:
      name: alpha
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    apiVersion: kubeadm.k8s.io/v1beta4
    nodeRegistration:
      name: gamma
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    apiVersion: kubeadm.k8s.io/v1beta4
    nodeRegistration:
      name: segma
networking:
  disableDefaultCNI: false
  # Ensuring internal resolution of host.docker.internal often requires no extra config on Mac 
  # but sometimes `extraPortMappings` or DNS patches are needed if we were not using the special DNS name.
