kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: paradox
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      name: alpha
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        hostname-override: "alpha"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      name: gamma
      kubeletExtraArgs:
        hostname-override: "gamma"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      name: segma
      kubeletExtraArgs:
        hostname-override: "segma"
networking:
  disableDefaultCNI: false
